export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const CREATE_THEATERS = "CREATE_THEATERS";
export const GET_THEATERS = "GET_THEATERS";
export const UPDATE_THEATERS = "UPADTE_THEATERS";
export const DELETE_THEATERS = "DELETE_THEATERS";
export const DELETE_ALL_THEATERS = "DELETE_ALL_THEATERS";

export const GET_PERFORMANCE = "GET_PERFORMANCE";
export const CREATE_PERFORMANCE = "CREATE_PERFORMANCE";
export const UPDATE_PERFORMANCE = "UPDATE_PERFORMANCE";
export const DELETE_PERFORMANCE = "DELETE_PERFORMANCE";

export const GET_GENRE = "GET_GENRE";
